package glyphs

var DEFAULT Glyph = Glyph{iconName: "◻️"}   // Default icon if none is specified
var NIL Glyph = Glyph{iconName: ""}         // Nil icon to represent no icon
var LAUNCH Glyph = Glyph{iconName: "🚀"}     // Icon for launching actions
var Back Glyph = Glyph{iconName: "◀️"}      // Icon for back actions
var Edit Glyph = Glyph{iconName: "✏️"}      // Icon for edit actions
var Delete Glyph = Glyph{iconName: "🗑️"}    // Icon for delete actions
var Projection Glyph = Glyph{iconName: "🔮"} // Icon for projection actions
var View Glyph = Glyph{iconName: "👁️"}      // Icon for view actions
var Add Glyph = Glyph{iconName: "🆕"}        // Icon for adding new items
var Save Glyph = Glyph{iconName: "💾"}       // Icon for saving actions
var Goal Glyph = Glyph{iconName: "🏁"}       // Icon for goal-related actions
var Users Glyph = Glyph{iconName: "👥"}      // Icon for user-related actions
var Home Glyph = Glyph{iconName: "🏠"}       // Icon for home actions
var Settings Glyph = Glyph{iconName: "⚙️"}  // Icon for settings actions
var Search Glyph = Glyph{iconName: "🔍"}     // Icon for search actions
var Dashboard Glyph = Glyph{iconName: "📋"}  // Icon for dashboard actions
var Chart Glyph = Glyph{iconName: "📈"}      // Icon for chart-related actions
var Profile Glyph = Glyph{iconName: "🪪"}    // Icon for profile-related actions
var Logout Glyph = Glyph{iconName: "🚪"}     // Icon for logout actions
var Error Glyph = Glyph{iconName: "❌"}      // Icon for error messages
var Success Glyph = Glyph{iconName: "✅"}    // Icon for success messages
var Warning Glyph = Glyph{iconName: "⚠️"}   // Icon for warning messages
var Info Glyph = Glyph{iconName: "ℹ️"}      // Icon for informational messages
var Close Glyph = Glyph{iconName: "🛑"}      // Icon for closing actions
var Login Glyph = Glyph{iconName: "🔑"}      // Icon for login actions
var User Glyph = Glyph{iconName: "👤"}       // Icon for user-related actions
var Print Glyph = Glyph{iconName: "🖨️"}     // Icon for print actions
var Help Glyph = Glyph{iconName: "？"}       // Icon for help actions
var Weight Glyph = Glyph{iconName: "⚖️"}    // Icon for weight-related actions
var Height Glyph = Glyph{iconName: "📏"}     // Icon for height-related actions
var Calendar Glyph = Glyph{iconName: "📅"}   // Icon for calendar-related actions
var Reset Glyph = Glyph{iconName: "🔄"}      // Icon for reset actions
