package glyphs

var DEFAULT Glyph = Glyph{iconName: "bi bi-circle"}               // Default icon if none is specified
var NIL Glyph = Glyph{iconName: ""}                               // Nil icon to represent no icon
var LAUNCH Glyph = Glyph{iconName: "bi bi-rocket-takeoff"}        // Icon for launching actions
var Back Glyph = Glyph{iconName: "bi bi-arrow-left"}              // Icon for back actions
var Edit Glyph = Glyph{iconName: "bi bi-pencil"}                  // Icon for edit actions
var Delete Glyph = Glyph{iconName: "bi bi-trash"}                 // Icon for delete actions
var Projection Glyph = Glyph{iconName: "bi bi-graph-up"}          // Icon for projection actions
var View Glyph = Glyph{iconName: "bi bi-eye"}                     // Icon for view actions
var Add Glyph = Glyph{iconName: "bi bi-plus"}                     // Icon for adding new items
var Save Glyph = Glyph{iconName: "bi bi-save"}                    // Icon for saving actions
var Goal Glyph = Glyph{iconName: "bi bi-flag"}                    // Icon for goal-related actions
var Users Glyph = Glyph{iconName: "bi bi-people"}                 // Icon for user-related actions
var Home Glyph = Glyph{iconName: "bi bi-house"}                   // Icon for home actions
var Settings Glyph = Glyph{iconName: "bi bi-gear"}                // Icon for settings actions
var Search Glyph = Glyph{iconName: "bi bi-search"}                // Icon for search actions
var Dashboard Glyph = Glyph{iconName: "bi bi-speedometer2"}       // Icon for dashboard actions
var Chart Glyph = Glyph{iconName: "bi bi-bar-chart"}              // Icon for chart-related actions
var Profile Glyph = Glyph{iconName: "bi bi-person-circle"}        // Icon for profile-related actions
var Logout Glyph = Glyph{iconName: "bi bi-box-arrow-right"}       // Icon for logout actions
var Error Glyph = Glyph{iconName: "bi bi-exclamation-triangle"}   // Icon for error messages
var Success Glyph = Glyph{iconName: "bi bi-check-circle"}         // Icon for success messages
var Warning Glyph = Glyph{iconName: "bi bi-exclamation-circle"}   // Icon for warning messages
var Info Glyph = Glyph{iconName: "bi bi-info-circle"}             // Icon for informational messages
var Close Glyph = Glyph{iconName: "bi bi-x-circle"}               // Icon for closing actions
var Login Glyph = Glyph{iconName: "bi bi-box-arrow-in-right"}     // Icon for login actions
var User Glyph = Glyph{iconName: "bi bi-person"}                  // Icon for user-related actions
var Print Glyph = Glyph{iconName: "bi bi-printer"}                // Icon for print actions
var Help Glyph = Glyph{iconName: "bi bi-question-circle"}         // Icon for help actions
var Weight Glyph = Glyph{iconName: "bi bi-weight"}                // Icon for weight-related actions
var Height Glyph = Glyph{iconName: "bi bi-arrows-angle-contract"} // Icon for height-related actions
var Calendar Glyph = Glyph{iconName: "bi bi-calendar"}            // Icon for calendar-related actions
var Reset Glyph = Glyph{iconName: "bi bi-arrow-clockwise"}        // Icon for reset actions
