package glyphs

var Default Glyph = Glyph{iconName: "fa-circle"}               // Default icon if none is specified
var Plus Glyph = Glyph{iconName: "fa-plus"}                    // Icon for adding items
var Edit Glyph = Glyph{iconName: "fa-edit"}                    // Icon for editing items
var Delete Glyph = Glyph{iconName: "fa-trash"}                 // Icon for deleting items
var View Glyph = Glyph{iconName: "fa-eye"}                     // Icon for viewing items
var Search Glyph = Glyph{iconName: "fa-search"}                // Icon for searching items
var Save Glyph = Glyph{iconName: "fa-save"}                    // Icon for saving items
var Cancel Glyph = Glyph{iconName: "fa-times"}                 // Icon for canceling actions
var Download Glyph = Glyph{iconName: "fa-download"}            // Icon for downloading items
var Upload Glyph = Glyph{iconName: "fa-upload"}                // Icon for uploading items
var Settings Glyph = Glyph{iconName: "fa-cog"}                 // Icon for settings or configuration
var Home Glyph = Glyph{iconName: "fa-home"}                    // Icon for home or dashboard
var Help Glyph = Glyph{iconName: "fa-question-circle"}         // Icon for help or support
var Info Glyph = Glyph{iconName: "fa-info-circle"}             // Icon for information
var Warning Glyph = Glyph{iconName: "fa-exclamation-triangle"} // Icon for warnings
var Error Glyph = Glyph{iconName: "fa-times-circle"}           // Icon for errors
var Success Glyph = Glyph{iconName: "fa-check-circle"}         // Icon for success messages
var Loading Glyph = Glyph{iconName: "fa-spinner"}              // Icon for loading states
var Logout Glyph = Glyph{iconName: "fa-sign-out-alt"}          // Icon for logging out
var Login Glyph = Glyph{iconName: "fa-sign-in-alt"}            // Icon for logging in
var Profile Glyph = Glyph{iconName: "fa-user"}                 // Icon for user profile
var Notifications Glyph = Glyph{iconName: "fa-bell"}           // Icon for notifications
var Calendar Glyph = Glyph{iconName: "fa-calendar"}            // Icon for calendar or scheduling
var Chart Glyph = Glyph{iconName: "fa-chart-bar"}              // Icon for charts or analytics
var File Glyph = Glyph{iconName: "fa-file"}                    // Icon for files or documents
var Folder Glyph = Glyph{iconName: "fa-folder"}                // Icon for folders or directories
var Link Glyph = Glyph{iconName: "fa-link"}                    // Icon for links or URLs
var Lock Glyph = Glyph{iconName: "fa-lock"}                    // Icon for security or locked items
var Unlock Glyph = Glyph{iconName: "fa-unlock"}                // Icon for unlocked items
var Trash Glyph = Glyph{iconName: "fa-trash-alt"}              // Icon for trash or recycle bin
var Print Glyph = Glyph{iconName: "fa-print"}                  // Icon for printing
var Share Glyph = Glyph{iconName: "fa-share-alt"}              // Icon for sharing items
var ArrowUp Glyph = Glyph{iconName: "fa-arrow-up"}             // Icon for upward actions
var ArrowDown Glyph = Glyph{iconName: "fa-arrow-down"}         // Icon for downward actions
var ArrowLeft Glyph = Glyph{iconName: "fa-arrow-left"}         // Icon for leftward actions
var ArrowRight Glyph = Glyph{iconName: "fa-arrow-right"}       // Icon for rightward actions
var Check Glyph = Glyph{iconName: "fa-check"}                  // Icon for confirming actions
var Times Glyph = Glyph{iconName: "fa-times"}                  // Icon for canceling or closing actions
var PlusSquare Glyph = Glyph{iconName: "fa-plus-square"}       // Icon for adding items in a square format
var MinusSquare Glyph = Glyph{iconName: "fa-minus-square"}     // Icon for removing items in a square format
var Sync Glyph = Glyph{iconName: "fa-sync"}                    // Icon for synchronizing or refreshing
var Bell Glyph = Glyph{iconName: "fa-bell"}                    // Icon for notifications or alerts
var Globe Glyph = Glyph{iconName: "fa-globe"}                  // Icon for global or international actions
var Star Glyph = Glyph{iconName: "fa-star"}                    // Icon for favorites or important items
var Heart Glyph = Glyph{iconName: "fa-heart"}                  // Icon for likes or favorites
var Camera Glyph = Glyph{iconName: "fa-camera"}                // Icon for camera or photo actions
var Video Glyph = Glyph{iconName: "fa-video"}                  // Icon for video actions
var Music Glyph = Glyph{iconName: "fa-music"}                  // Icon for music or audio actions
var Book Glyph = Glyph{iconName: "fa-book"}                    // Icon for books or reading materials
var Pencil Glyph = Glyph{iconName: "fa-pencil-alt"}            // Icon for writing or editing text
var Map Glyph = Glyph{iconName: "fa-map"}                      // Icon for maps or locations
var Compass Glyph = Glyph{iconName: "fa-compass"}              // Icon for navigation or direction
var Shield Glyph = Glyph{iconName: "fa-shield-alt"}            // Icon for security or protection
var Nil Glyph = Glyph{iconName: ""}                            // Nil icon for cases where no icon is needed
